package com.malds.groceriesProject.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;

import lombok.Data;

@Data
@DynamoDBTable(tableName = "Client")
public class Client {

    // data members
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private Integer clientID;

    private String email;

    private String firstName;

    private String lastName;

    @DynamoDBTypeConvertedEnum
    private Enum gender;

    private String dateOfBirth;

    private String zipcode;

    public Client() {
        this.clientID = null;
        this.email = null;
        this.firstName = null;
        this.lastName = null;
        this.gender = null;
        this.dateOfBirth = null;
        this.zipcode = null;
    }
    
    @Override
    public String toString() {
        return "\nClient { " +
                "\n\t clientID=" + clientID +
                ",\n\t email=" + email +
                ",\n\t firstName='" + firstName + '\'' +
                ",\n\t lastName='" + lastName + '\'' +
                "\n\t gender='" + gender + 
                '\'' +
                "\n\t dateOfBirth='" + dateOfBirth + 
                '\'' +
                "\n\t zipcode='" + zipcode + 
                '\'' +
                '}';
    }
}
