package com.malds.groceriesProject.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;

@Data
@DynamoDBTable(tableName = "Client")
public class Client {

    // data members
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String clientID;

    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    private String firstName;

    @DynamoDBAttribute
    private String lastName;

    @DynamoDBAttribute
    private String gender;

    @DynamoDBAttribute
    private String dateOfBirth;

    @DynamoDBAttribute
    private String zipcode;

    public Client() {
        this.clientID = null;
        this.email = null;
        this.firstName = null;
        this.lastName = null;
        this.gender = null;
        this.dateOfBirth = null;
        this.zipcode = null;
    }
}
