package com.malds.groceriesProject.models;

import java.util.Hashtable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;

@Data
@DynamoDBTable(tableName = "Product")
public class Product {

    // data members
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private Integer productID;

    private Integer vendorID;

    private double price;

    private Integer quantity;

    private Hashtable<String, String> additionalFeatures = new Hashtable<>();

    public Product() {
        this.productID = null;
        this.vendorID = null;
        this.price = 0.0;
        this.quantity = 0;
        this.additionalFeatures = null;
    }
    
    @Override
    public String toString() {
        return "\nProduct { " +
                "\n\t productID=" + productID +
                ",\n\t vendorID=" + vendorID +
                ",\n\t price='" + price + '\'' +
                ",\n\t quantity='" + quantity + '\'' +
                '\'' +
                "\n\t additionalFeatures='" + additionalFeatures + 
                '\'' +
                '}';
    }
}
