package com.malds.groceriesProject.models;

import java.util.Map;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "ShoppingList")
public class ShoppingList {
    /**
     * DynamoDBAttribute: shoppingListID. type: String Hash Key
     */
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String shoppingListID;

    /**
     * DynamoDBAttribute: clientID. type: String
     */
    @DynamoDBAttribute
    private String clientID;

    /**
     * DynamoDBAttribute: productIDToQuantity. type: Map<String,String>
     */
    @DynamoDBAttribute
    private Map<String, String> productIDToQuantity;
}
