package com.malds.groceriesProject.models;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;

@Data
@AllArgsConstructor
@DynamoDBTable(tableName = "ShoppingList")
public class ShoppingList {

    // data members
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String shoppingListID;

    @DynamoDBAttribute
    private Integer clientID;

    @DynamoDBAttribute
    private Integer productID;
    
    public ShoppingList() {
        this.shoppingListID = null;
        this.clientID = null;
        this.productID = null;
    }
}
