package com.malds.groceriesProject.models;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;

@Data
@DynamoDBTable(tableName = "ShoppingList")
public class ShoppingList {

    // data members
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private Integer shoppingListID;

    private Integer clientID;

    private Integer productID;
    
    public ShoppingList() {
        this.shoppingListID = null;
        this.clientID = null;
        this.productID = null;
    }
    
    @Override
    public String toString() {
        return "\nShoppingList { " +
                "\n\t shoppingListID=" + shoppingListID +
                ",\n\t clientID=" + clientID +
                ",\n\t productID='" + productID + '\'' +
                '}';
    }
}
