package com.malds.groceriesProject.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;

@Data
@DynamoDBTable(tableName = "Vendor")
public class Vendor {

    // data members
    /**
     * DynamoDBAttribute: vendorID. type: String Hash Key
     */
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String vendorID;

    /**
     * DynamoDBAttribute: email. type: String
     */
    private String email;

    /**
     * DynamoDBAttribute: companyName. type: String
     */
    private String companyName;

    /**
     * DynamoDBAttribute: industry. type: String
     */
    private String industry;

    /**
     * DynamoDBAttribute: zipcode. type: String
     */
    private String zipcode;

    /**
     * Vendor default constructor.
     */
    public Vendor() {
        this.vendorID = null;
        this.email = null;
        this.companyName = null;
        this.industry = null;
        this.zipcode = null;
    }
}
