package com.malds.groceriesProject.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;

@Data
@DynamoDBTable(tableName = "Vendor")
public class Vendor {

    // data members
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private Integer vendorID;

    private String email;

    private String companyName;

    private String industry;

    private String zipcode;

    public Vendor() {
        this.vendorID = null;
        this.email = null;
        this.companyName = null;
        this.industry = null;
        this.zipcode = null;
    }


    @Override
    public String toString() {
        return "\nVendor { " + "\n\t vendorID=" + vendorID + ",\n\t email=" + email
                + ",\n\t companyName='" + companyName + '\'' + ",\n\t industry='" + industry + '\''
                + '\'' + "\n\t zipcode='" + zipcode + '\'' + '}';
    }
}
