# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# Workflow name
name: CI/CD Pipeline

on:
  # configuring build workflow to run on push events, but only when the push includes changes to .java files, the Maven
  # pom.xml for the project, or when the build workflow itself is changed
  push:
    branches: [ main ]
    paths: [ '**.java', '.github/workflows/build.yml', 'pom.xml' ]
  pull_request:
    branches: [ main ]

jobs:
  # define job for maven build
  build-and-test:
    # run on ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      # check out repository
      - name: Checkout
        uses: actions/checkout@v3
      # checking out a branch for badges
      - name: Checkout badges branch to a branch directory
        uses: actions/checkout@v3
        with:
          ref: badges
          path: badges
      # Set up JDK 11
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Build Groceries Project
        working-directory: ./groceriesProject
        run: mvn -B package --file pom.xml
